### ISSUE TITLE
Rundeck 2.6.10 is not starting

### ISSUE THREAD

**Issue by nilroy** [Webtrends/rundeck#104]
The latest version of rundeck does not start because of the web.xml file that has been used in this cookbook. Anyone working on it?

**Comment by nilroy** [comment]
This PR https://github.com/Webtrends/rundeck/pull/105 fixes it

**Comment by nilroy** [comment]
@pcross616 kindly review

**Comment by pcross616** [comment]
looks like we are missing the correct attributes.. https://github.com/nilroy/rundeck/blob/f62dbfa1f588ceca8661bec2c5c8ee135c0fc158/attributes/default.rb#L7-L11
