### ISSUE TITLE
Requesting write access to this repository

### ISSUE THREAD

**Issue by atheiman** [Webtrends/rundeck#144]
@pcross616 could I be granted write permissions to this repository? Im fortunate enough that my employer is allowing me time to work on this cookbook because bug fixes and enhancements to this cookbook will benefit our team. However, if pull requests are sitting for an extended time it slows us down - and we're trying very quickly to setup Rundeck in all of our environments.

I feel like my contributions to this point for this repository are significant enough to demonstrate I can be trusted with this responsibility. I will only approve and merge pull requests that ...

- have passing tests (I've added these and plan to enforce them)
- are backwards compatible (unless that is not reasonably possible)
- correctly adjust the metadata version according to semantic versioning

If I have any doubt on a change, I will only "approve" or "request changes" and then ask for your opinion.

Our team is very invested in this cookbook, let me help out more with write permissions: https://help.github.com/articles/adding-outside-collaborators-to-repositories-in-your-organization/

**Comment by atheiman** [comment]
@joshgillingham @BrotherNumsy could either of you help me gain write access to this repository?

**Comment by pcross616** [comment]
Done, thx for your support with this cookbook.

**Comment by atheiman** [comment]
excellent, thank you!
