### ISSUE TITLE
requesting permissions to push tags to supermarket

### ISSUE THREAD

**Issue by atheiman** [Webtrends/rundeck#146]
@pcross616 @jmickle @ev0ldave - I see you have pushed tags to https://supermarket.chef.io/cookbooks/rundeck in the past. Since Ive received permissions to write to this github repository, I was hoping I could also have permissions to push tags to https://supermarket.chef.io/cookbooks/rundeck?

Here is my supermarket user profile https://supermarket.chef.io/users/atheiman

It should be as simple as

- log in to the supermarket with your Chef account: https://supermarket.chef.io/sign-in
- go to the rundeck cookbook page: https://supermarket.chef.io/cookbooks/rundeck
- click `Manage Cookbook -> Add Collaborator` on the right
- add me `atheiman`

Thanks!

**Comment by pcross616** [comment]
Yup I added you.

**Comment by atheiman** [comment]
thanks
