### ISSUE TITLE
Write access to this repo

### ISSUE THREAD

**Issue by nilroy** [Webtrends/rundeck#156]
@pcross616 We are using rundeck in our environment. I have been creating PRs to this repo from the last couple of years. I think I could be a good contributor to this repo by creating PRs, doing reviews etc., and I can assure that I would not do any changes without peer review. Sometimes long review time is slowing us down heavily. I would appreciate if you could allow me doing more for this repo.

**Comment by pcross616** [comment]
Let me see what I can do

**Comment by nilroy** [comment]
@pcross616 Thanks a lot for letting me in.

**Comment by nilroy** [comment]
@pcross616 I have been revoked of the write access for this repo. What happened? Did I do something wrong?

**Comment by pcross616** [comment]
The all the GH repos are currently transitioning to Oracle and have been put in RO mode for the time being.  (Oracle has bought Webtrends Infinity see https://www.oracle.com/corporate/acquisitions/infinity/index.html) and Oracle is now going to be sponsoring the cookbooks and services hosted at Webtrends GH org.

I will let you know when the transfer is done (I am working on it right now)


Pete

On Apr 14, 2017, at 2:52 PM, Nilanjan Roy <notifications@github.com<mailto:notifications@github.com>> wrote:


@pcross616<https://github.com/pcross616> I have been revoked of the write access for this repo. What happened? Did I do something wrong?

**Comment by atheiman** [comment]
could we move this cookbook to github.com/rundeck/rundeck-cookbook? I think that would be a better location for this repo, and it would get more attention from Rundeck developers.

**Comment by atheiman** [comment]
@gschueler would you be open to this? ⬆️

**Comment by gschueler** [comment]
Hi @atheiman not at this time. I think it would be better left as a community project managed by people who use it.
