### ISSUE TITLE
Can't update to new version of rundeck

### ISSUE THREAD

**Issue by holycow001** [Webtrends/rundeck#44]
I'm trying to install rundeck-2.4.2-1-GA.deb. I override the override['rundeck']['deb']['package'] = 'rundeck-2.4.2-1-GA.deb' & override['rundeck']['checksum'] = 'd2038440542b64921449e4ea0d7899f723bb29a58d713532fb8a0ab434ddac89'.

When i run the cookbook, i get 

 ================================================================================
           Error executing action `install` on resource 'apt_package[http://download.rundeck.org/deb/rundeck-2.4.2-1-GA.deb]'
           ================================================================================

           Chef::Exceptions::Package
           -------------------------
       dpkg failed - #<Process::Status: pid 27164 exit 2>!

**Comment by pcross616** [comment]
seems the package is failing to install.

if you run dpkg -i rundeck-2.4.2-1-GA.deb what do you get?

Is this an upgrade?

**Comment by holycow001** [comment]
it installs without errors...

Preparing to unpack rundeck-2.4.2-1-GA.deb ...
Unpacking rundeck (2.4.2) over (2.4.2) ...
Setting up rundeck (2.4.2) ...
usermod: no changes
Processing triggers for ureadahead (0.100.0-16) ...

**Comment by pcross616** [comment]
That’s odd it says it was installed already.  Can you remove it and run chef-client in debug mode.

**Comment by holycow001** [comment]
sorry about that, i spun up a new server and received the same error. ssh'd to the box, wget'd the rundeck .deb file and ran dpkg -i. Here's the out put.

root@default-ubuntu-1404:/home/vagrant# dpkg -i rundeck-2.4.2-1-GA.deb
Selecting previously unselected package rundeck.
(Reading database ... 81604 files and directories currently installed.)
Preparing to unpack rundeck-2.4.2-1-GA.deb ...
Unpacking rundeck (2.4.2) ...
Setting up rundeck (2.4.2) ...
Processing triggers for ureadahead (0.100.0-16) ...

**Comment by holycow001** [comment]
Closing this issue. I grabbed the cookbook from Github instead of supermarket and that fixed the issue.

**Comment by pcross616** [comment]
Ah yes trying to get the market place cookbook updated but having an issue with that.  Thanks for reminding me.

Sent from my Windows Phone
________________________________
