### ISSUE TITLE
Cookbook is not working with rundeck version 2.5

### ISSUE THREAD

**Issue by tomkregenbild** [Webtrends/rundeck#47]
It seems that since the upgrade to version 2.5 of rundeck and the upgrade of grails to 2.4.4 together with this version there are problems that cause the server to fail after running chef.

1. in order for the rundeckd service to start without failing I had to comment out the following parts in "/var/lib/rundeck/exp/webapp/WEB-INF/web.xml":

        <filter>
                <filter-name>sitemesh</filter-name>
                <filter-class>org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter</filter-class>
        </filter>

        <filter-mapping>
                <filter-name>sitemesh</filter-name>
                <url-pattern>/*</url-pattern>
                <dispatcher>REQUEST</dispatcher>
                <dispatcher>ERROR</dispatcher>
        </filter-mapping>

2. After it starts the webserver is unable to retrieve any images and static files - I see the project and the I am able to login but it is all HTML text.

Can you suggest what is needed in order to make it work with the latest version?

**Comment by tomkregenbild** [comment]
any update on this?

**Comment by pcross616** [comment]
I have not had a second to look at it but I know we want to upgrade internally so I am sure we can get this fixed as part of that.

@ev0ldave ??

**Comment by tomkregenbild** [comment]
Do you know when you are going to make the internal upgrade?

**Comment by pcross616** [comment]
we just release 2.0.7 version of the cookbook that should fix this
