### ISSUE TITLE
Support for custom configuration 

### ISSUE THREAD

**Issue by nilroy** [Webtrends/rundeck#57]
It would be very useful if there is support for custom configuration option.

**Comment by nilroy** [comment]
I added few lines for supporting this in framework.properties file. Its now the pull request that I already created a week earlier.

**Comment by jennyfountain** [comment]
This would be very helpful. I don't see anywhere to enable clustering.

**Comment by pcross616** [comment]
ya thats a good idea, I am sure it wouldn't be hard since the db is already a config options and you could just put it behind a LB.
