### ISSUE TITLE
Release v2.0.7?

### ISSUE THREAD

**Issue by aboutte** [Webtrends/rundeck#58]
Am I missing something or should there be a v2.0.7 release?  I see version 2.0.7 on the SuperMarket (https://supermarket.chef.io/cookbooks/rundeck) but no version that matches in GitHub.  

Master is very close but there are differences (installation of slack plugin, variable data bag name).

**Comment by pcross616** [comment]
https://github.com/Webtrends/rundeck/releases/tag/v2.0.7
