### ISSUE TITLE
I don't want to use apache reverse proxy

### ISSUE THREAD

**Issue by nilroy** [Webtrends/rundeck#70]
Hi,

Presently the cookbook will install apache2 by default and configure it to be used as reverse proxy. What if I don't want to use apache and use some other stuff instead. I think we could make this configurable like whether to use reverse proxy or not. I can do the changes and create a PR. But before doing that just wanted to share it with you @pcross616 

Thanks & Regards
Nilanjan

**Comment by pcross616** [comment]
just use 'server_install' recipe if you don't want apache2.  The 'server_dependancy' installs java also optional to use, but rundeck does require java to be installed on the system.

**Comment by nilroy** [comment]
Ahh great
