### ISSUE TITLE
Latest Rundeck Requires Java 7 but Java Cookbook Defaults to 6

### ISSUE THREAD

**Issue by iAnomaly** [Webtrends/rundeck#87]
Hi there!

First, thanks for this awesome cookbook!

However, Rundeck install is failing for me because it looks for Java 7 (or 8) but your use of the Java cookbook is installing Java 6 by default. For now I have added `default[:java][:jdk_version] = '7'` to my downstream cookbook, but you should consider adding `default[:java][:jdk_version] = '7'` to your attributes file.

Thanks,
Cameron

**Comment by ARentz07** [comment]
@iAnomaly 💡 For future reference, feel free to open a pull request with these types of minor updates. 

#88 should fix this. Please review.
