### ISSUE TITLE
Support data bag for RDBMS

### ISSUE THREAD

**Issue by ARentz07** [Webtrends/rundeck#92]
In order to support encryption of DB user name and password, we should support using a data bag to store this config.

**Comment by ARentz07** [comment]
Note that my team has already staged a code change for this and would like to contribute.

**Comment by pcross616** [comment]
Go for it..

**Comment by ARentz07** [comment]
I've opened a (rather large) PR to fix this along with the other issues recently logged: https://github.com/Webtrends/rundeck/pull/96

Would this be something we'd be able to review or should it be broken out separately?
