### ISSUE TITLE
Is ACLPolicies data bag really required?

### ISSUE THREAD

**Issue by bernardoVale** [Webtrends/rundeck#99]
Hi, I'm trying to use this cookbook to deploy a rundeck environment. I just want A default ACL policy but it seems the code it's expecting me to configure at least one policy using the data bag.

There is no example in the documentation. Could someone help me with that? An example or a way to run the code without having to configure this?

**Comment by ARentz07** [comment]
I'll test this out. Seems like the intention was for this to be not required, but there could be a bug or false assumption we're making in the code.

**Comment by nilroy** [comment]
This PR https://github.com/Webtrends/rundeck/pull/105 makes the aclpolicies as an optional stuff
